root: none
name: webtext-500m
data_name: webtext
max_size: 1024
grad_accum: 1
batch_size: 1
save_every: 100
warmup_steps: 10
lr: 3.0e-4
num_workers: 16
model_config:
  bunch_size: 4
  hidden_size: 1024
  num_layers: 42
  num_heads: 16
  head_size: 64
distributed: false
grad_checkpoints: 20
ema: false