root: none
name: webtext-500m
data_name: webtext
max_size: 1024
grad_accum: 1
batch_size: 1
save_every: 1000
warmup_steps: 10
lr: 3.0e-4
num_workers: 16
model_config:
  bunch_size: 8
  hidden_size: 2048
  num_layers: 64
  num_heads: 32
  head_size: 64
distributed: false
grad_checkpoints: 64
ema: false