root: /scratch/work/public/ml-datasets/pile/train/
name: greene-500m
data_name: pile
max_size: 2048
grad_accum: 4
batch_size: 2
save_every: 10
warmup_steps: 100
lr: 3.0e-4
num_workers: 8
model_config:
  bunch_size: 8
  hidden_size: 512
  num_layers: 20
  num_heads: 8
  head_size: 64
distributed: false
ema: false
