root: none
name: webtext-500m
data_name: webtext
max_size: 2048
grad_accum: 8
batch_size: 1
save_every: 1000
warmup_steps: 100
lr: 3.0e-4
num_workers: 16
model_config:
  bunch_size: 4
  hidden_size: 512
  num_layers: 64
  num_heads: 8
  head_size: 64
distributed: false
grad_checkpoints: 32
ema: false