root: /scratch/work/public/ml-datasets/pile/train/
name: greene-3b
data_name: pile
max_size: 8192
grad_accum: 32
save_every: 10
batch_size: 1
warmup_steps: 100
model_config:
  bunch_size: 16
  hidden_size: 1024
  num_layers: 96
  num_heads: 16
  head_size: 128
lr: 2.0e-4
distributed: true
