root: none
name: webtext-500m
data_name: webtext
max_size: 512
grad_accum: 32
batch_size: 1
save_every: 10
warmup_steps: 100
lr: 2.0e-4
num_workers: 1
model_config:
  bunch_size: 8
  num_embed_bunch: 8
  hidden_size: 512
  num_layers: 80
  num_heads: 16
  head_size: 64
distributed: false
ema: false