root: /scratch/work/public/ml-datasets/pile/train/
name: greene-500m
data_name: pile
max_size: 2048
grad_accum: 32
batch_size: 1
save_every: 10
warmup_steps: 100
lr: 3.0e-4
num_workers: 8
model_config:
  bunch_size: 8
  hidden_size: 2048
  num_layers: 96
  num_heads: 32
  head_size: 64
distributed: true
grad_checkpoints: 64
ema: false
