root: /scratch/work/public/ml-datasets/pile/train/
name: greene-500m
data_name: pile
max_size: 1024
grad_accum: 32
batch_size: 1
save_every: 10
warmup_steps: 100
lr: 3.0e-4
num_workers: 8
model_config:
  bunch_size: 8
  hidden_size: 1024
  num_layers: 80
  num_heads: 8
  head_size: 64
distributed: false
ema: false
