root: /scratch/work/public/ml-datasets/pile/train/
name: greene-500m
data_name: pile
max_size: 4096
grad_accum: 32
batch_size: 8
warmup_steps: 0
lr: 1.0e-4
model_config:
  bunch_size: 8
  hidden_size: 512
  num_layers: 80
  num_heads: 16
  head_size: 64
distributed: true
