name: ai4ce
data_name: webtext
max_size: 1024
grad_accum: 32
batch_size: 1
warmup_steps: 0
model_config:
  bunch_size: 8
  hidden_size: 512
  num_layers: 80
  num_heads: 16
  head_size: 64
distributed: true
