name: ai4ce
data_name: webtext
max_size: 1024
grad_accum: 100
batch_size: 8
warmup_steps: 100
model_config:
  bunch_size: 2
  hidden_size: 512
  num_layers: 24
  num_heads: 16
  head_size: 64
ddp: false