name: ai4ce
data_name: webtext
max_size: 512
grad_accum: 32
batch_size: 32
warmup_steps: 0
model_config:
  bunch_size: 2
  hidden_size: 512
  num_layers: 24
  num_heads: 16
  head_size: 64
distributed: false
num_workers: 1
ema: false
